"""empty message

Revision ID: 588390ea3b21
Revises: 230a926ac1dc
Create Date: 2019-12-13 11:29:01.281169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588390ea3b21'
down_revision = '230a926ac1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_user', sa.Column('_password', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_user', '_password')
    # ### end Alembic commands ###
